project:
  type: book

book:
  title: "Community Building Handbook"
  author: 
    - Anica Araneta
    - Weronika Filinger
    - Aman Goel
    - Ella Kaye
    - Saskia Lawson-Tovey
    - Oscar Seip
    - Samantha Wittke
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd

format: 
  html:
    theme: cosmo