project:
  type: book

book:
  title: "Community Building Handbook"
  author: 
    - Aman Goel
    - Anica Araneta
    - Ella Kaye
    - Oscar Seip
    - Samantha Wittke
    - Saskia Lawson-Tovey
    - Weronika Filinger
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - who.qmd
    - organise.qmd
    - sustain.qmd
    - grow.qmd
    - edia.qmd
  repo-url: https://github.com/EllaKaye/community-building-handbook
  repo-actions: [edit]

format: 
  html:
    theme: cosmo