## Welcome! {.unnumbered}

This is a community building handbook for those for whom community building is not their main job!

There are a broad range of different communities in the Research Software space, and running these communities requires work. Whilst large communities, such as the Software Sustainability Institute, employ Community Managers (capital C, capital M), most smaller communities are run by volunteers, or by people for whom it is a small part of their overall role. While being part of these communities may be associated with their job, the role of running it is usually not recognised as an essential part of their work. We’ll call these people community managers (small c, small m), because whilst they are managing a community, it’s not a recognised role.

Such community managers may come to community management in an ad hoc way, either starting their own communities or assuming responsibility for existing communities. It is unlikely that they have received training or even guidance on community management. They are probably learning as they go, both about what community management involves in principle, and the practical aspects of running the community.

This guide is written by such people, for such people! We want to share what we’ve learnt about managing a community, whilst acknowledging that community management is likely a small part of your professional role, or not officially part of it at all. We want you to know what we wish we had known when we started out. We want to provide you with practical suggestions and resources that you need to run a community, specifically for when you don’t have much time for running said community.

In this regard, this handbook provides a first practical introduction to community management. If you are already a Community Manager, or are interested in becoming recognised as one, there are excellent training courses and resources in the Research Software or other technical/scientific worlds, such as those provided by [The Centre for Scientific Collaboration and Community Engagement (CSCCE)](https://www.cscce.org/). [The Turing Way](https://book.the-turing-way.org/) is also developing a [Research Community Manager pathway](https://github.com/the-turing-way/the-turing-way/issues/4164).


## Acknowledgements {.unnumbered}

The initial version of this repository has been created during the Software Sustainability Institute Collaborations Workshop 2025 Hack Day.